// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cE-kWYi4oUeqpldZ8tOmHfS0ib7Zv6A',
    appId: '1:639361302101:web:ac4a6eda5a2199f8bc5edc',
    messagingSenderId: '639361302101',
    projectId: 'fir-app-5f614',
    authDomain: 'fir-app-5f614.firebaseapp.com',
    storageBucket: 'fir-app-5f614.appspot.com',
    measurementId: 'G-HBPN55G881',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOKf3EqlzT0P1vLRXoCdw1JKvx11pbzd4',
    appId: '1:639361302101:android:84ae1f8217fd473ebc5edc',
    messagingSenderId: '639361302101',
    projectId: 'fir-app-5f614',
    storageBucket: 'fir-app-5f614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDG45fARCvZa9W_zKCTD1y2ZQkoRyahyA',
    appId: '1:639361302101:ios:7b2dacb30fb341e9bc5edc',
    messagingSenderId: '639361302101',
    projectId: 'fir-app-5f614',
    storageBucket: 'fir-app-5f614.appspot.com',
    iosBundleId: 'com.qudratsoftech.chatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDG45fARCvZa9W_zKCTD1y2ZQkoRyahyA',
    appId: '1:639361302101:ios:df8fce15cbc537babc5edc',
    messagingSenderId: '639361302101',
    projectId: 'fir-app-5f614',
    storageBucket: 'fir-app-5f614.appspot.com',
    iosBundleId: 'com.qudratsoftech.chatapplication.RunnerTests',
  );
}
